server:
  port: 3001
spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/fz972/springcoud-config.git
          search-paths: springcoud-config
#          username:
#          password: