server:
  port: 9527

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
# spring配置
spring:
  application:
    name: springcloud-zuul

# Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka/
  instance:
    instance-id: springcloud-zuul # 修改eureka上的默认描述信息
    prefer-ip-address: true


# info配置
info:
  app.name: springcloud
  company.name: ccahouse
zuul:
  routes:
    mydept.serviceId: springcloud-provider
    mydept.path: /mydept/**
  ignored-services: "*"